repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: python -m flake8
        types: [python]
        exclude: setup.py
